python "main.py" \
 --base configs/stable-diffusion/v1-finetune_unfrozen.yaml \
 -t \
 --actual_resume "parallel6.ckpt" \
 --reg_data_root "/workspace/Dreambooth-Stable-Diffusion/regularization_images/person_ddim" \
 -n "parallel6" \
 --gpus 0, \
 --data_root "/workspace/Dreambooth-Stable-Diffusion/train" \
 --max_training_steps 15655 \
 --no-test \
 --token "notoken"